### ISSUE TITLE
createJSInteropWrapper does not appear 

### ISSUE THREAD

**Issue by volkaankarakus** [p-mazhnik/flutter-embedding#11]
The library 'dart:js_interop' doesn't export a member with the shown name 'createJSInteropWrapper'.
Try removing the name from the list of shown members.

**Comment by volkaankarakus** [comment]
When I updated dart and flutter, this problem disappeared, but this time I still encounter such a problem.

<img width="1108" alt="Screenshot 2024-02-26 at 16 12 37" src="https://github.com/p-mazhnik/flutter-embedding/assets/64658867/2b877577-e3ad-4043-ab9d-3f3010f684d6">

**Comment by volkaankarakus** [comment]
Later, when I replace HTMLElement with HTMLElementView, I get a problem directly related to package:web as follows.
<img width="1000" alt="Screenshot 2024-02-26 at 16 21 31" src="https://github.com/p-mazhnik/flutter-embedding/assets/64658867/ca6e2882-af34-4f5f-983e-0997e44112d7">

**Comment by p-mazhnik** [comment]
Hi @volkaankarakus , thanks for the report! 

I recently bumped Dart sdk constraints: `sdk: ">=3.3.0 <4.0.0"`.
And `createJSInteropWrapper` is available starting from the latest Flutter version (3.19). 

Can you try reverting the custom changes in this file? I see in your screenshots that `dart:js` is used. Please also make sure you re-installed the dependencies after Flutter upgrade. 

Note that app can be built in CI/CD system, and the current version was successfully deployed to https://p-mazhnik.github.io/flutter-embedding/react/, so the issue most likely related to your local setup

**Comment by volkaankarakus** [comment]
I solved this part, thank you very much. I wrote the integration codes on the flutter side as in this repo, but I have almost no knowledge on the react part. I also read the README section, but I cannot apply the template I have to a project. Can you help me, please?
